project_id = "isnezquuwepqcjkaupjh"

[functions.create_payment_intent]
verify_jwt = true

[functions.stripe_webhook]
verify_jwt = false

[functions.get_payment_methods]
verify_jwt = true

[functions.save_payment_method]
verify_jwt = true

[functions.delete_payment_method]
verify_jwt = true

[functions.generate_report]
verify_jwt = true

[functions.validate_quote]
verify_jwt = true

[functions.performance_monitor]
verify_jwt = true

[functions.real_time_sync]
verify_jwt = true