// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isnezquuwepqcjkaupjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzbmV6cXV1d2VwcWNqa2F1cGpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDA0MjEsImV4cCI6MjA3MDYxNjQyMX0.a7tTT1l98O1m1HSV7iUWxqs8lp5x3FUugCTXZ0MhZYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});